model_name: "cnn"

# Embedding cfg
embedding_dim: 512

# CNN cfg
model_in: 512    # Embedding.py will modify this cfg automatically
cnn_out: 512
kernal_size: 3
padding: 1
fc_hid: 768
dropout: 0.3
n_layers: 2
model_out: 512

# Classifier
use_dist: True
use_cos: True
cls_hid: 256

# train config
EPOCH: 20
batch_size: 32
k_fold: 5
lr: 8e-6
weight_decay: 1e-3