model_name: "cnn"

# Embedding Cfg
embedding_dim: 80



# CNN Cfg
kernel_size: 3
in_channels: 160    # Embedding.py will modify this cfg automatically
cnn_hid_channels: 512
cnn_out_channels: 1024

fc_hid_channels: 256


# train config
use_GPU: True
gpu_id: 0

EPOCH: 10
batch_size: 32
k_fold: 5
lr: 3e-4
weight_decay: 1e-3