model_name: "rnn"

# Embedding cfg
embedding_dim: 512

# RNN cfg
model_in: 512    # Embedding.py will modify this cfg automatically
rnn_hid: 256
n_layers: 4
dropout: 0.3
bidirection: True
model_out: 1024

# Classifier
use_dist: True
use_cos: True
cls_hid: 256

# train config
use_GPU: True
gpu_id: 1

EPOCH: 10
batch_size: 32
k_fold: 5
lr: 8e-5
weight_decay: 1e-3