model_name: "transformer"

# Embedding cfg
embedding_dim: 512

# Transformer cfg
transformer_in: 512    # Embedding.py will modify this cfg automatically
transformer_n_layers: 2
transformer_n_heads: 4
transformer_out: 512

# RNN cfg
rnn_in: 512
rnn_hid: 256
rnn_n_layers: 4
rnn_dropout: 0.2
rnn_bidirection: True
rnn_out: 2048

# Classifier
classifier_in: 2048
use_sum: False
use_dist: True
use_cos: True


# train config
use_GPU: True
gpu_id: 1

EPOCH: 20
batch_size: 32
k_fold: 5
lr: 8e-4
weight_decay: 1e-3