# current working directory
cwd: "."

defaults:
  - preprocess
  - model: rnn

use_GPU: True
gpu_id: 1

model_dir: "./code/model_files/"
test_with_best_model: True
result_file: "./prediction_result/result.tsv"

test_only: False